[package]
name = "lsp-microcad"
version = "0.1.0"
edition = "2024"
authors = [
    "Patrick Hoffmann <p.hoffmann@berlin.de>",
    "Michael Winkelmann <michael@winkelmann.site>",
]
description = "vscode server backend for microcad"
license = "AGPL-3.0-or-later"
repository = "https://github.com/rustfahrtagentur/microcad"
keywords = ["vscode", "microcad", "editor"]
categories = ["Programming Languages"]

[dependencies]
log = "0.4"
env_logger = "0.11.8"
tower-lsp = "0.20"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.18"

[[bin]]
name = "microcad-lsp-client"
path = "src/client.rs"

[[bin]]
name = "microcad-lsp"
path = "src/server.rs"
